mode: train
data_path: ./datasets/out/
model_path: ./models/dev/
output_path: ./rollouts/dev/
output_filename: rollout

# 開発用（〜1時間）
batch_size: 32
noise_std: 0.00067

nmessage_passing_steps: 2
latent_dim: 128
mlp_hidden_dim: 256
particle_type_embedding_size: 16
connectivity_radius: 0.05

train_scenes: 256
valid_scenes: 64

ntraining_steps: 10000
validation_interval: 200
nsave_steps: 1000

eval_rollout_steps: 20

lr_init: 0.0001
lr_decay: 0.1
lr_decay_steps: 20000

amp: fp16
grad_accum: 2
num_workers: 4
prefetch_factor: 2
pin_memory: true
persistent_workers: true
seed: 0

early_stop_check_step: 2000
early_stop_required_improvement: 0.3

ckpt_keep: 3
model_file: null
train_state_file: null
cuda_device_number: null

